### PR TITLE
Adding spectator.earth

### PR DESCRIPTION
**Pull request by bheliom**
Hi! Great list! Just adding another one.

### CODE REVIEW

**Comment by kr-stn** [comment]
Thank you for this PR.

Is the app in a state where it can be used? I tried to set-up a channel as well as track the satellites in real-time. Both failed with current versions of Chrome and Firefox (or I am clicking the wrong buttons). I don't see what it would add to the current set of tools.

**Comment by bheliom** [comment]
Yes, although it's in beta so some bugs still to be cleaned. There's been an issue with one of the satellites which caused your problems. Fixed now, thanks to your feedback 👏 . 

Regarding adding to the list, seems like most of the tools have a common denominator and Spectator adds tracking Sentinels and overpass computation and soon much more. If I misunderstood the idea for this list, please feel free to decline the PR.

**Comment by kr-stn** [comment]
Sorry for the late reply, I am swamped at work right now.

Now that I am able to create the channels I can see the appeal of this tool. Being able to get the overpass times for an AOI is indeed very cool!

Do you estimate the overpass times from the data provided by the satellite ground stations or are you using some kind of API provided?

**Comment by bheliom** [comment]
Wow, took me only two months to discover your question ;)

We're actually relying on multiple sources for overpass estimation, observations made by ground stations being the core for all satellites. For better estimation we use additional data but that largely depends on which satellite we're talking about. Obviously for Sentinels we get plenty of information, so we can get pretty good estimates.

**Pull request merged**
